apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo-one
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.5-0
  postgresVersion: 14
  service:
    type: LoadBalancer
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        storageClassName: pgo-gp2
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.40-0
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: pgo-gp2
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
  # Enable pgnodemx
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: pgnodemx
          pgnodemx.kdapi_enabled: on
          pgnodemx.kdapi_path: /etc/database-containerinfo
