apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pgo-gp2
parameters:
  encrypted: "true"
  fsType: ext4
  type: gp2
mountOptions:
  - discard
reclaimPolicy: Delete
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer